---
title: "Projekt Zaliczeniowy"
author: "Piotr Rzadkowski, Jan Masternak"
date: "20.01.2023"
output: html_document
---
# Projekt 

Projekt polega na prostym opracowaniu statystycznym wyników porównania działania wybranych algorytmów minimalizacji stochastycznej. Do porównania zostałe wybrane algorytmy **Poszukiwania przypadkowego PRS** oraz **Algorytm Multi-Start MS**.

Działanie algorytmów sprawdzane było na podstawie dwóch funkcji skalarnych, wielomodalnych i posiadających wersje dla różnej liczby wymiarów. Wybrane zostały funkcje **Ackley'a** (dziedzina: -32.768; 32.768; wartość minimalna: 0) oraz **Rosenbrock'a** (dziedzina: -5; 10; wartość minimalna: 0).

Użyte biblioteki: smoof, ecr.

```{R}
if (!requireNamespace("ecr", quietly = TRUE)) {
    install.packages("ecr")
}
if (!requireNamespace("smoof", quietly = TRUE)) {
    install.packages("smoof")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
    install.packages("ggplot2")
}
```

```{R setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{R}
library(ecr)
library(ggplot2)
library(smoof)
```

```{R}
ackley_range <- c(-32.768, 32.768)
ackley_R2 <- makeAckleyFunction(2L)
ackley_R10 <- makeAckleyFunction(10L)
ackley_R20 <- makeAckleyFunction(20L)
```

```{R}
rosenbrock_range <- c(-5, 10)
rosenbrock_R2 <- makeRosenbrockFunction(2L)
rosenbrock_R10 <- makeRosenbrockFunction(10L)
rosenbrock_R20 <- makeRosenbrockFunction(20L)
```

```{R}
find_min_prs <- function(f, n, range) {
    R <- getParamLengths(getParamSet(f))
    min_v <- Inf
    for (i in 1:n) {
        v <- c(runif(R, range[1], range[2]))
        min_v <- min(min_v, f(v))
    }
    return(min_v)
}
prs_rep <- function(f, size, n, range) {
    y <- replicate(size, find_min_prs(f, n, range))
    return(y)
}
```

```{R}
find_min_ms <- function(f, n, range) {
    R <- getParamLengths(getParamSet(f))
    points <- matrix(0, nrow = n, ncol = R)
    for (i in 1:n) {
        points[i, ] <- runif(R, range[1], range[2])
    }
    min_v <- Inf
    lower <- replicate(R, range[1])
    upper <- replicate(R, range[2])
    calls <- 0
    for (i in 1:n) {
        result <- optim(points[i, ], f, lower = lower, upper = upper, method = "L-BFGS-B")
        min_v <- min(min_v, result$value)
        calls <- calls + result$counts[1]
    }
    return(c(min_v, calls))
}
ms_rep <- function(f, size, n, range) {
    result <- matrix(0, nrow = size, ncol = 2)
    for (i in 1:size) {
        result[i, ] <- find_min_ms(f, n, range)
    }
    y <- result[, 1]
    calls <- result[, 2]
    return(list(y, mean(calls)))
}
```

```{R}
test_runner <- function(f, size, starting_points_n, range) {
    res <- ms_rep(f, size, starting_points_n, range)
    ms <- res[[1]] # minima found by MS
    calls <- res[[2]] # mean of calls
    prs <- prs_rep(f, size, calls, range) # mean of minima with same number of calls as MS
    return(c(ms = list(ms), prs = list(prs), ms_min = mean(ms), prs_min = mean(prs)))
}
```

```{R}
check_hypothesis <- function(ms, prs) {
    if_passed <- function(p_value) {
        if (p_value < 0.05) {
            return("Odrzucono hipotezę zerową, na rzecz hipotezy alternatywnej")
        } else {
            return("Nie odrzucono hipotezy zerowej")
        }
    }
    print(paste("Wynik hipotezy dla ms (One Sample t-test):", if_passed(t.test(ms)$p.value)))

    print(paste("Wynik hipotezy dla prs (One Sample t-test):", if_passed(t.test(prs)$p.value)))

    print(paste("Wynik hipotezy dla ms i prs (Two Sample t-test):", if_passed(t.test(ms, prs)$p.value)))
}
```

Test_runner zwraca następujące wartości: \* ms_min - średnia z minima znalezionych przez MS \* prs_min - średnia z minima znalezionych przez PRS \* ms_hist - histogram minima znalezionych przez MS (zapisany jako funkcja) \* prs_hist - histogram minima znalezionych przez PRS (zapisany jako funkcja) \* ms_prs_boxplot - boxplot minima znalezionych przez MS i PRS (zapisany jako funkcja)

```{R}
n <- 100 # number of starting points
size <- 50 # number of repetitions
```

### Hipotezy dotyczące przedziałow ufności (One Sample t-test):

-   Hipoteza zerowa - funkcja ma minimum równe 0

-   Hipoteza alternatywna - funckja nie ma minimum równego 0

### Hipotezy dotyczące porównywania funkcji algorytmami (Two Sample t-test):

-   Hipoteza zerowa - algorytmy MS i PRS dają jednakowe wyniki

-   Hipoteza alternatywna - algorytmy MS i PRS nie dają jednakowych wyników

```{R}
f <- ackley_R2
range <- ackley_range # range of starting points
result <- test_runner(f, size, n, range)
result$ms_min
result$prs_min
ms <- result$ms
prs <- result$prs
hist(ms, main = "Histogram minimów znalezionych przez MS dla funkcji Ackley w 2 wymiarach", xlab = "Minima znalezione przez MS")
hist(prs, main = "Histogram minimów znalezionych przez PRS dla funkcji Ackley w 2 wymiarach", xlab = "Minima znalezione przez PRS")
boxplot(ms, prs, names = c("MS", "PRS"), main = "Wykres pudełkowy minimów znalezionych przez MS i PRS dla funkcji Ackley w 2 wymiarach", ylab = "Minima znalezione przez MS i PRS")
```

Wykres (MS) dla Ackley R2 daje wyniki minimów leżące stosunkowo blisko zera
(mieszczące się w przedziale [0,1]), co rzeczywiście powinno zajść. 

Wykres (PRS) dla Ackley R2 daje wyniki w znacznej mierze odbiegające od zera
(większość w przedziale [2,6]), co jest dalekie od zera.

Z wykresów pudełkowych można zaobserwować, że mediana dla MS znajduje się blisko zera, czyli oczekiwanej wartości. Natomiast w przypadku PRS mediana wynosie mniej więcej 4, czyli jest daleka od zera. Zakres międzykwartylowy dla PRS jest mniejszy niż ten dla MS.   

```{R}
check_hypothesis(ms,prs)
```

```{R}
f <- ackley_R10
range <- ackley_range # range of starting points
result <- test_runner(f, size, n, range)
result$ms_min
result$prs_min
ms <- result$ms
prs <- result$prs
hist(ms, main = "Histogram minimów znalezionych przez MS dla funkcji Ackley w 10 wymiarach", xlab = "Minima znalezione przez MS")
hist(prs, main = "Histogram minimów znalezionych przez PRS dla funkcji Ackley w 10 wymiarach", xlab = "Minima znalezione przez PRS")
boxplot(ms, prs, names = c("MS", "PRS"), main = "Wykres pudełkowy minimów znalezionych przez MS i PRS dla funkcji Ackley w 10 wymiarach", ylab = "Minima znalezione przez MS i PRS")
```

Zarówno w przypadku MS jak i PRS wykresy dały wyniki niezgodne z rzeczywistą
postacią rzeczy (MS - większość w przedziale [17,19], PRS - więkoszość
w przedziale [17,19])

Wykresy pudełkowe są niemal identyczne - w obu przypadkach mediana znacznie odbiega od zera (wynosi mniej więcej 18). W obu przypadkach pojawiły się pojedyncze wartości bliższe oczekiwanemu zeru, jednak były w mniejszości.

```{R}
check_hypothesis(ms,prs)
```

```{R}
f <- ackley_R20
range <- ackley_range # range of starting points
result <- test_runner(f, size, n, range)
result$ms_min
result$prs_min
ms <- result$ms
prs <- result$prs
hist(ms, main = "Histogram minimów znalezionych przez MS dla funkcji Ackley w 20 wymiarach", xlab = "Minima znalezione przez MS")
hist(prs, main = "Histogram minimów znalezionych przez PRS dla funkcji Ackley w 20 wymiarach", xlab = "Minima znalezione przez PRS")
boxplot(ms, prs, names = c("MS", "PRS"), main = "Wykres pudełkowy minimów znalezionych przez MS i PRS dla funkcji Ackley w 20 wymiarach", ylab = "Minima znalezione przez MS i PRS")
```

Zarówno w przypadku MS jak i PRS wykresy dały wyniki niezgodne z rzeczywistą
postacią rzeczy (MS - większość w przedziale [18.6,19], PRS - więkoszość
w przedziale [19,20])

W obu przypadkach skupienie minimów jest dalekie od zera, choć dla PRS odbiega bardziej niż dla MS. Podobnie jak w przypadku powyżej wystąpiły nieliczne minima bliższe oczekiwanemu zeru (zarówno dla MS, jak i PRS).

```{R}
check_hypothesis(ms,prs)
```

```{R}
f <- rosenbrock_R2
range <- rosenbrock_range # range of starting points
result <- test_runner(f, size, n, range)
result$ms_min
result$prs_min
ms <- result$ms
prs <- result$prs
hist(ms, main = "Histogram minimów znalezionych przez MS dla funkcji Rosenbrock w 2 wymiarach", xlab = "Minima znalezione przez MS")
hist(prs, main = "Histogram minimów znalezionych przez PRS dla funkcji Rosenbrock w 2 wymiarach", xlab = "Minima znalezione przez PRS")
boxplot(ms, prs, names = c("MS", "PRS"), main = "Wykres pudełkowy minimów znalezionych przez MS i PRS dla funkcji Rosenbrock w 2 wymiarach", ylab = "Minima znalezione przez MS i PRS")
```

Zarówno w przypadku wykresu MS, jak i PRS otrzymane wyniki pokazują, że ustalone minima są bliskie zeru. Więkoszą skuteczność miał MS (więkoszość wartości znajduje się w zakresie [0,10^-9]), podczas gdy dla PRS jest to przedział [0,0.2].

Wykres pudełkowy MS odpowiada minimom, które są niemal równe zeru. W przypadku PRS skupienie minimów jest nieco bardziej oddalone od zera, choć dalej te wartości są stosunkowo podobne do wartości oczekiwanej. W przypadku PRS wystąpiło znacznie więcej wartosci odbiegających. Przestrzeń międzykwartylowa jest zdecydowanie większa dla PRS niż dla MS. 

```{R}
check_hypothesis(ms,prs)
```

```{R}
f <- rosenbrock_R10
range <- rosenbrock_range # range of starting points
result <- test_runner(f, size, n, range)
result$ms_min
result$prs_min
ms <- result$ms
prs <- result$prs
hist(ms, main = "Histogram minimów znalezionych przez MS dla funkcji Rosenbrock w 10 wymiarach", xlab = "Minima znalezione przez MS")
hist(prs, main = "Histogram minimów znalezionych przez PRS dla funkcji Rosenbrock w 10 wymiarach", xlab = "Minima znalezione przez PRS")
boxplot(ms, prs, names = c("MS", "PRS"), main = "Wykres pudełkowy minimów znalezionych przez MS i PRS dla funkcji Rosenbrock w 10 wymiarach", ylab = "Minima znalezione przez MS i PRS")
```

W przypadku użycia MS otrzymane minima są bliskie 0, co widać na wykesie.

W przypadku PRS wyniki nie odzwierciedlają rzeczywistej postaci rzeczy w najmniejszym stopniu - znacznie odbiegają od zera.

W przypadku MS wyciągnięto wnioski podobne jak wyżej. 

Tutaj wyniki otrzymane dla PRS znacznie odbiegają od oczekiwanego zera.

```{R}
check_hypothesis(ms,prs)
```

```{R}
f <- rosenbrock_R20
range <- rosenbrock_range # range of starting points
result <- test_runner(f, size, n, range)
result$ms_min
result$prs_min
ms <- result$ms
prs <- result$prs
hist(ms, main = "Histogram minimów znalezionych przez MS dla funkcji Rosenbrock w 20 wymiarach", xlab = "Minima znalezione przez MS")
hist(prs, main = "Histogram minimów znalezionych przez PRS dla funkcji Rosenbrock w 20 wymiarach", xlab = "Minima znalezione przez PRS")
boxplot(ms, prs, names = c("MS", "PRS"), main = "Wykres pudełkowy minimów znalezionych przez MS i PRS dla funkcji Rosenbrock w 20 wymiarach", ylab = "Minima znalezione przez MS i PRS")
```

Dla 20 wymiarów wyniki algorytmów są bardzo podobne jak w przypadku 10 wymiarów (dotyczy to też wykresów pudełkowych).

```{R}
check_hypothesis(ms,prs)
```
